In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\Shaik Yunus\\Downloads\\clinic_visits.csv")

In [3]:
df

,visit_id,patient_id,age,gender,department,diagnosis,visit_type,wait_time_min,cost_usd,admitted
0,1001,P001,34,Female,General Medicine,Hypertension,New,18,80,No
1,1002,P002,67,Male,Cardiology,Arrhythmia,Follow-up,42,220,Yes
2,1003,P003,15,Female,Pediatrics,Asthma,New,25,60,No
3,1004,P004,52,Male,Orthopedics,Back Pain,New,30,150,No
4,1005,P005,73,Female,Cardiology,Heart Failure,Follow-up,55,500,Yes
5,1006,P006,28,Female,Dermatology,Eczema,New,12,45,No
6,1007,P007,61,Male,General Medicine,Diabetes,Follow-up,20,95,No
7,1008,P008,9,Male,Pediatrics,Fever,New,35,50,No
8,1009,P009,46,Female,Neurology,Migraine,New,27,180,No
9,1010,P010,58,Male,Orthopedics,Arthritis,Follow-up,40,210,Yes
10,1011,P011,39,Female,General Medicine,Anemia,New,16,70,No
11,1012,P012,82,Female,Cardiology,Chest Pain,New,48,320,Yes
12,1013,P013,22,Male,Dermatology,Acne,Follow-up,10,55,No
13,1014,P014,65,Female,Neurology,Stroke Review,Follow-up,14,260,No
14,1015,P015,31,Male,General Medicine,Flu,New,10,65,No

In [4]:
print(df.head())

   visit_id patient_id  age  gender        department      diagnosis  \
0      1001       P001   34  Female  General Medicine   Hypertension
1      1002       P002   67    Male        Cardiology     Arrhythmia
2      1003       P003   15  Female        Pediatrics         Asthma
3      1004       P004   52    Male       Orthopedics      Back Pain
4      1005       P005   73  Female        Cardiology  Heart Failure

  visit_type  wait_time_min  cost_usd admitted
0        New             18        80       No
1  Follow-up             42       220      Yes
2        New             25        60       No
3        New             30       150       No
4  Follow-up             55       500      Yes

In [5]:
print(df.shape)

(15, 10)

In [6]:
print(df.dtypes)

visit_id          int64
patient_id       object
age               int64
gender           object
department       object
diagnosis        object
visit_type       object
wait_time_min     int64
cost_usd          int64
admitted         object
dtype: object

In [7]:
print(df[['patient_id', 'department', 'cost_usd']])

   patient_id        department  cost_usd
0        P001  General Medicine        80
1        P002        Cardiology       220
2        P003        Pediatrics        60
3        P004       Orthopedics       150
4        P005        Cardiology       500
5        P006       Dermatology        45
6        P007  General Medicine        95
7        P008        Pediatrics        50
8        P009         Neurology       180
9        P010       Orthopedics       210
10       P011  General Medicine        70
11       P012        Cardiology       320
12       P013       Dermatology        55
13       P014         Neurology       260
14       P015  General Medicine        65

In [8]:
df[df['department'] == 'Cardiology']

,visit_id,patient_id,age,gender,department,diagnosis,visit_type,wait_time_min,cost_usd,admitted
1,1002,P002,67,Male,Cardiology,Arrhythmia,Follow-up,42,220,Yes
4,1005,P005,73,Female,Cardiology,Heart Failure,Follow-up,55,500,Yes
11,1012,P012,82,Female,Cardiology,Chest Pain,New,48,320,Yes

In [9]:
df[df['wait_time_min'] > 30]

,visit_id,patient_id,age,gender,department,diagnosis,visit_type,wait_time_min,cost_usd,admitted
1,1002,P002,67,Male,Cardiology,Arrhythmia,Follow-up,42,220,Yes
4,1005,P005,73,Female,Cardiology,Heart Failure,Follow-up,55,500,Yes
7,1008,P008,9,Male,Pediatrics,Fever,New,35,50,No
9,1010,P010,58,Male,Orthopedics,Arthritis,Follow-up,40,210,Yes
11,1012,P012,82,Female,Cardiology,Chest Pain,New,48,320,Yes

In [10]:
df[df['age'] >= 60]

,visit_id,patient_id,age,gender,department,diagnosis,visit_type,wait_time_min,cost_usd,admitted
1,1002,P002,67,Male,Cardiology,Arrhythmia,Follow-up,42,220,Yes
4,1005,P005,73,Female,Cardiology,Heart Failure,Follow-up,55,500,Yes
6,1007,P007,61,Male,General Medicine,Diabetes,Follow-up,20,95,No
11,1012,P012,82,Female,Cardiology,Chest Pain,New,48,320,Yes
13,1014,P014,65,Female,Neurology,Stroke Review,Follow-up,14,260,No

In [11]:
df[df['visit_type'] == 'Follow-up']

,visit_id,patient_id,age,gender,department,diagnosis,visit_type,wait_time_min,cost_usd,admitted
1,1002,P002,67,Male,Cardiology,Arrhythmia,Follow-up,42,220,Yes
4,1005,P005,73,Female,Cardiology,Heart Failure,Follow-up,55,500,Yes
6,1007,P007,61,Male,General Medicine,Diabetes,Follow-up,20,95,No
9,1010,P010,58,Male,Orthopedics,Arthritis,Follow-up,40,210,Yes
12,1013,P013,22,Male,Dermatology,Acne,Follow-up,10,55,No
13,1014,P014,65,Female,Neurology,Stroke Review,Follow-up,14,260,No

In [12]:
df['cost_usd'].max()
df['cost_usd'].min()

45

In [13]:
len(df)

15

In [14]:
df[df['admitted'] == 'Yes'].shape[0]

4

In [15]:
df_sorted = df.sort_values(by='wait_time_min', ascending=False)
df_sorted.head()

,visit_id,patient_id,age,gender,department,diagnosis,visit_type,wait_time_min,cost_usd,admitted
4,1005,P005,73,Female,Cardiology,Heart Failure,Follow-up,55,500,Yes
11,1012,P012,82,Female,Cardiology,Chest Pain,New,48,320,Yes
1,1002,P002,67,Male,Cardiology,Arrhythmia,Follow-up,42,220,Yes
9,1010,P010,58,Male,Orthopedics,Arthritis,Follow-up,40,210,Yes
7,1008,P008,9,Male,Pediatrics,Fever,New,35,50,No

In [16]:
def age_category(age):
    if age < 18:
        return 'Child'
    elif age <= 59:
        return 'Adult'
    else:
        return 'Senior'

df['age_group'] = df['age'].apply(age_category)

df[['age', 'age_group']].head()

   age age_group
0   34     Adult
1   67    Senior
2   15     Child
3   52     Adult
4   73    Senior